{"Launchpad":"https://bugs.launchpad.net/bugs/1440154","Id":"1440154","Gerrit":"https://review.openstack.org/177517","IdGerrit":"177517","IdCommit":"5490bddf804281f76fc9ae8289c1f44976f4b5a4","Files":["cinder/tests/unit/test_emc_vmax.py","cinder/volume/drivers/emc/emc_vmax_common.py","cinder/volume/drivers/emc/emc_vmax_fc.py","cinder/volume/drivers/emc/emc_vmax_iscsi.py"],"Lines_Inseted":136,"Lines_Deleted":29,"CommitParent":"c57aef777ce70a51b4c46ac4c9de4cc3eb854ec5","Classification":"Unknown","KeywordsTitle":"fails, not result, cleaned up","Description":"was added, cleanup, should fail, could be considered bug, ","KeywordsCommit":"Clean up failed, this patch catches, exception, removes.","Comments":"I'm not sure, in the description the author has doubts about where his requirements should be."}