{"Launchpad":"https://bugs.launchpad.net/bugs/1498964","Id":"1498964","Gerrit":"https://review.openstack.org/235282","IdGerrit":"235282","IdCommit":"61026d4e4f2a58dd84ffb2e4e40ab99860b9316a","Files":["cinder/locale/cinder-log-error.pot","cinder/locale/cinder-log-info.pot","cinder/locale/cinder-log-warning.pot","cinder/locale/cinder.pot","cinder/locale/tr_TR/LC_MESSAGES/cinder.po","cinder/tests/unit/test_emc_vmax.py","cinder/tests/unit/test_huawei_drivers.py","cinder/tests/unit/volume/drivers/netapp/dataontap/client/test_api.py","cinder/volume/drivers/emc/emc_vmax_common.py","cinder/volume/drivers/netapp/dataontap/client/api.py"],"Lines_Inseted":1,"Lines_Deleted":1169,"CommitParent":"b22c3d695beb375aca99f28941c0a19d66815b26","Classification":"Bug","KeywordsTitle":"migration, fix, ","Description":"migration fails, not taken into account, necessary","KeywordsCommit":"merge, release tag, will apear, contains, please, later conflicts","Comments":"It's a bug report, in the description of the commit doesn't appear the closes-bug as in SZZ algorithm."}