{"Launchpad":"https://bugs.launchpad.net/bugs/1499251","Id":"1499251","Gerrit":"https://review.openstack.org/227200","IdGerrit":"227200","IdCommit":"d93ca8b7f888a54004825542924280608e62f689","Files":["cinder/tests/unit/test_huawei_drivers.py","cinder/volume/drivers/huawei/huawei_driver.py","cinder/volume/drivers/huawei/huawei_utils.py"],"Lines_Inseted":21,"Lines_Deleted":4,"CommitParent":"78cd21b1c9c429792024596f608c6a6d5d583fa2","Classification":"Bug","KeywordsTitle":"Fix update, issue","Description":"old version, new version, assumes, read failed, will happen, ","KeywordsCommit":"Fix update, assumes, new version, old version, will read, fails, will happen, ","Comments":"It's a bug report"}