{"Launchpad":"https://bugs.launchpad.net/bugs/1502166","Id":"1502166","Gerrit":"https://review.openstack.org/235974","IdGerrit":"235974","IdCommit":"5cbf00b624e6c2bb8597d82640a1cb61b9405ba6","Files":["cinder/tests/unit/test_netapp_eseries_iscsi.py","cinder/volume/drivers/netapp/eseries/library.py"],"Lines_Inseted":2,"Lines_Deleted":2,"CommitParent":"c9eef31820dc385a2c9f4ba24dd1d194f9e7d088","Classification":"Bug","KeywordsTitle":"fails","Description":"fail, error_deleting, regression","KeywordsCommit":"fix deletion of missing volume, exeption, KeyError, VolumeNotFound, catches, logs a debug, restores compatibility","Comments":""}