{"Launchpad":"https://bugs.launchpad.net/bugs/1414515","Id":"1414515","Gerrit":"https://review.openstack.org/149923","IdGerrit":"149923","IdCommit":"7c387637614871fac460955c0ea3beb139ae168c","Files":["nova/servicegroup/api.py","nova/servicegroup/drivers/base.py","nova/servicegroup/drivers/db.py","nova/servicegroup/drivers/zk.py","nova/tests/unit/servicegroup/test_zk_driver.py"],"Lines_Inseted":36,"Lines_Deleted":77,"CommitParent":"5a9d7abb98ffc9af8380fdf6429915f80bb19656","Classification":"Bug","KeywordsTitle":"FakeLoopingCall","Description":"FakeLoopingCall, fake, pass, not necessary","KeywordsCommit":"Fix up, returned a fakeLoopingCall, wasn't used, removes it","Comments":"It's a bug report"}
