{"Launchpad":"https://bugs.launchpad.net/bugs/1475356","Id":"1475356","Gerrit":"https://review.openstack.org/205686","IdGerrit":"205686","IdCommit":"cb2a8fbb13975d9a3fd0c953a93f7e2088570a02","Files":["nova/objects/base.py","nova/tests/unit/objects/test_objects.py"],"Lines_Inseted":8,"Lines_Deleted":3,"CommitParent":"5b252f126420daf8da1d45c56df09f75cc322640","Classification":"Bug","KeywordsTitle":"wrong supported version","Description":"object that failed to deserialize,","KeywordsCommit":"Fix serializer supported version,  This patch fixes the serializer ","Comments":"Faulty Serializer"}