{"Launchpad":"https://bugs.launchpad.net/bugs/1398468","Id":"1398468","Gerrit":"https://review.openstack.org/165658","IdGerrit":"165658","IdCommit":"8b80fe7766d4b816bca8f03d4d7adbb4b2876c7d","Files":["openstack_dashboard/dashboards/project/instances/templates/instances/_instance_flavor.html","openstack_dashboard/dashboards/project/instances/views.py"],"Lines_Inseted":12,"Lines_Deleted":7,"CommitParent":"947bc63977134472eaf0e7fb5ca2f1b2bab3836a","Classification":"Bug","KeywordsTitle":"Unable","Description":"get error, ","KeywordsCommit":"Fix terminated, it failed because,","Comments":""}