{"Launchpad":"https://bugs.launchpad.net/bugs/1478143","Id":"1478143","Gerrit":"https://review.openstack.org/205709","IdGerrit":"205709","IdCommit":"49f9d15488b115a49a97bb65a74dee9886060d65","Files":["openstack_dashboard/api/keystone.py","openstack_dashboard/dashboards/identity/users/forms.py"],"Lines_Inseted":10,"Lines_Deleted":9,"CommitParent":"20d4685df9847972337473063091da3972941de3","Classification":"Bug","KeywordsTitle":"","Description":"is no longer, replaced, error, Server error, whitout changing","KeywordsCommit":"Update, create, changed, throws an exception","Comments":"It's a bug report, they have changed the name of a parameter and is no longer honored and throws an exception"}