{"Launchpad":"https://bugs.launchpad.net/bugs/1398779","Id":"1398779","Gerrit":"https://review.openstack.org/138688","IdGerrit":"138688","IdCommit":"72d41174765540bb7672b545c336fb7aaad075e8","Files":["neutron/agent/linux/ra.py","neutron/tests/unit/test_l3_agent.py"],"Lines_Inseted":7,"Lines_Deleted":1,"CommitParent":"ae38d81b61d9111bffe3c5036b3ad16b1aa27f6d","Classification":"Bug","KeywordsTitle":"blocks, update","Description":"rewritten, switching, never completes, blocked, fix ","KeywordsCommit":"void, lock, doesn't, passes, closed, log messages, should work, update, will no proceed, could,  ","Comments":"It's a bug report, now the daemon doesn't conclude the update process "}