{"Launchpad":"https://bugs.launchpad.net/bugs/1411163","Id":"1411163","Gerrit":"https://review.openstack.org/197937","IdGerrit":"197937","IdCommit":"571453c614577ffd47e23de9a35863d2f2119583","Files":["neutron/api/rpc/handlers/dhcp_rpc.py","neutron/tests/unit/api/rpc/handlers/test_dhcp_rpc.py"],"Lines_Inseted":1,"Lines_Deleted":0,"CommitParent":"f9787afc348d7d386caf90ef8e9257bb0f9e002c","Classification":"Bug","KeywordsTitle":"failover","Description":"can't be created, debugging, ","KeywordsCommit":"Update, failover, not created, not updated, different, not created, will allow, ","Comments":"It's a bug report"}