{"Launchpad":"https://bugs.launchpad.net/bugs/1436890","Id":"1436890","Gerrit":"https://review.openstack.org/175796","IdGerrit":"175796","IdCommit":"c315cff05364664a5872c6a5dc6b9dc2d24fab39","Files":["neutron_vpnaas/services/vpn/device_drivers/ipsec.py","neutron_vpnaas/services/vpn/device_drivers/template/openswan/ipsec.conf.template"],"Lines_Inseted":16,"Lines_Deleted":2,"CommitParent":"72e1f670fdca2138aa85703cb96eac473f6fb811","Classification":"Bug","KeywordsTitle":"error","Description":"ERROR, failing, inconsistency, incomplete, problems, shouldn't use","KeywordsCommit":"is not working, will address, doesn't need , issue, No changes are required ,add ,fails to process.","Comments":"It's a bug report, some parameters were causing a bug using IPv6"}