{"Launchpad":"https://bugs.launchpad.net/bugs/1506934","Id":"1506934","Gerrit":"https://review.openstack.org/236886","IdGerrit":"236886","IdCommit":"0b5285aeccb482617b676e2c1278f829adc8cc2a","Files":["neutron/agent/l3/ha.py","neutron/tests/unit/agent/l3/test_agent.py"],"Lines_Inseted":1,"Lines_Deleted":1,"CommitParent":"7c5e0b6112e1d017a24ce13b42fa419ec99fd1e8","Classification":"Bug","KeywordsTitle":"Exception,  is wrong, not worke","Description":"error, log, KeyError, deleted, should be expected ","KeywordsCommit":"wrong, not work,","Comments":"It's a bug report, the exception type in the code was wrong, and the system fails."}